# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_status',
            field=models.TextField(default=b'ok'),
        ),
    ]
